---
- name: Sync the ansible directory
  synchronize:
    src: "{{ git_dir }}/ansible/"
    dest: "{{ ansible_deploy_dir }}/"
    recursive: yes
    delete: yes
  when: ansible_deploy_dir is defined
- name: Dump all variables to a var file.
  template:
    src: templates/vars.json.j2
    dest: "{{ ansible_deploy_dir }}/vars.json"
  when: ansible_deploy_dir is defined
- name: Delete the build directory
  file:
    path: "{{ build_dir }}"
    state: absent
- name: Recrete the build directory
  file:
    path: "{{ build_dir }}"
    state: directory
- name: Copy from {{ git_dir }}/src/ to the build dir.
  synchronize:
    src: "{{ git_dir }}/src/"
    dest: "{{ build_dir }}"
- name: Set site directory permissions
  file:
    path: "{{ build_site_dir }}"
    state: directory
    mode: "0755"
- name: Ensure the files directory exists
  file:
    state: directory
    path: "{{ files_dir }}"
    mode: "0775"
- name: Symlink files directory
  file:
    state: link
    src: "{{ files_dir }}"
    dest: "{{ build_files_dir }}"
    mode: "0775"
- name: Create settings.ENVIRONMENT.php
  template:
    src: "{{ git_dir }}/src/sites/default/settings.{{ t7_env }}.php"
    dest: "{{ build_site_dir }}/settings.{{ t7_env }}.php"
    mode: "0755"
