---
- name: Add Drupal to cron
  cron:
    name: "{{ drupal_cron_name }}"
    state: "{{ {true: 'present', false: 'absent'}[drupal_cron_present] | default('present') }}"
    hour: "{{ drupal_cron_hour }}"
    minute: "{{ drupal_cron_minute }}"
    job: "{{ drupal_cron_drush_path }} --root={{ drupal_cron_web_path }} --uri={{ drupal_cron_url }} cron"
    disabled: "{{ drupal_cron_disabled }}"
  when: drupal_cron_url is defined
