---
- name: check if a backup web directory exists
  stat:
    path: "{{ web_dir }}_old"
  register: web_dir_stat
- name: update the files directory permissions prior to deletion
  command: "find {{ web_dir }}_old -type d -exec chmod 755 {} \\;"
  when: web_dir_stat.stat.exists
- name: delete backup web directory if exists
  file:
    path: "{{ web_dir }}_old"
    state: absent
  when: web_dir_stat.stat.exists
- name: backup the web directory
  command: "mv {{ web_dir }} {{ web_dir }}_old"
  args:
    creates: "{{ web_dir }}_old"
    removes: "{{ web_dir }}"
- name: move the build directory to the web directory
  command: "mv {{ build_dir }} {{ web_dir }}"
  args:
    creates: "{{ web_dir }}"
    removes: "{{ build_dir }}"
